## Calculate score for each node in graph:

In [1]:
import pandas as pd
import pickle

with open("data/intermediate/nearest_categories.pkl", "rb") as f:
    nearest_categories: dict[str, pd.DataFrame] = pickle.load(f)

#for category, df in nearest_categories.items():
#    display(f"category: {category}", df.describe(), df.head())

In [2]:
import pandana as pdna

network = pdna.Network.from_hdf5("data/intermediate/denmark.backup")

Generating contraction hierarchies with 24 threads.
Setting CH node vector of size 7088328
Setting CH edge vector of size 7671244
Range graph removed 1386 edges of 15342488
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%

In [3]:
# Check what nodes in the network have categories within max_dist
dist_df = pd.concat(
    [df["dist"] for df in nearest_categories.values()], 
    axis=1
)

max_dist = 1600
nodes = network.nodes_df

nodes["score"] = (dist_df <= max_dist).sum(axis=1)
scored_nodes = nodes[nodes["score"] > 0]

display(scored_nodes.head(), len(scored_nodes.index))

           x          y  score
0  12.072963  55.634530      5
1  12.072729  55.634554      5
2  12.072263  55.634602      5
3  12.071127  55.634711      5
4  12.071045  55.634700      5

4582931

## Option 1: Merge scored nodes within same grid and average score:

In [14]:
import pygeohash as pgh
from shapely.geometry import box

# Compute hash for all nodes/points
scored_nodes["hash"] = [
    pgh.encode(latitude=lat, longitude=lon, precision=6)
    for lat, lon in zip(scored_nodes["y"], scored_nodes["x"])
]

# Merge all rows with colliding hashes and average their scores
grouped = scored_nodes \
    .groupby("hash", as_index=False) \
    .agg({"score": "mean"})

grouped["rectangle"] = grouped["hash"].apply(lambda hash: box(*pgh.get_bounding_box(hash)))
grouped = grouped[["rectangle", "score"]]

display(grouped.head(), grouped.describe())

/tmp/ipykernel_2318/12794975.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  scored_nodes["hash"] = [

                                           rectangle     score
0  POLYGON ((55.546875 8.118896484375, 55.546875 ...  2.000000
1  POLYGON ((55.546875 8.1298828125, 55.546875 8....  2.000000
2  POLYGON ((55.5413818359375 8.140869140625, 55....  2.000000
3  POLYGON ((55.546875 8.140869140625, 55.546875 ...  2.000000
4  POLYGON ((55.5413818359375 8.15185546875, 55.5...  1.210526

              score
count  42419.000000
mean       1.825547
std        1.000175
min        1.000000
25%        1.000000
50%        1.431818
75%        2.438786
max        5.000000

In [17]:
import geopandas as gpd
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:bachelordb123!@127.0.0.1:5432/gis")

gdf = gpd.GeoDataFrame(grouped, geometry="rectangle", crs=4326)
gdf.to_postgis(name="grid", con=engine, if_exists="replace")

## Option 2: Assign score to edges:

In [5]:
display(nodes.head(), len(nodes.index), network.edges_df.head(), len(network.edges_df.index))

           x          y  score
0  12.072963  55.634530      5
1  12.072729  55.634554      5
2  12.072263  55.634602      5
3  12.071127  55.634711      5
4  12.071045  55.634700      5

7091188

   from  to       dist
0     0   1  14.964623
1     1   2  29.692772
2     2   3  72.350900
3     3   4   5.289233
4     4   5  30.094357

7674433

In [6]:
from shapely.geometry import LineString

edges = network.edges_df.merge(
    nodes[["x", "y", "score"]],
    left_on="from",
    right_index=True,
).rename(columns={"x": "x_from", "y": "y_from", "score": "score_from"})

edges = edges.merge(
    nodes[["x", "y", "score"]],
    left_on="to",
    right_index=True,
).rename(columns={"x": "x_to", "y": "y_to", "score": "score_to"})

edges["linestring"] = edges.apply(
    lambda row: LineString([
        (row["x_from"], row["y_from"]),
        (row["x_to"], row["y_to"]),
    ]),
    axis=1
)

edges = edges[["linestring", "score_from", "score_to"]]
edges = edges[(edges["score_from"] > 0) | (edges["score_to"] > 0)]

display(edges.head(), len(edges.index))

                                          linestring  score_from  score_to
0  LINESTRING (12.072963 55.6345298, 12.0727285 5...           5         5
1  LINESTRING (12.0727285 55.6345541, 12.0722632 ...           5         5
2  LINESTRING (12.0722632 55.6346023, 12.0711266 ...           5         5
3  LINESTRING (12.0711266 55.6347107, 12.0710447 ...           5         5
4  LINESTRING (12.0710447 55.6346995, 12.0705787 ...           5         5

5096371

In [ ]:
import geopandas as gpd
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:bachelordb123!@127.0.0.1:5432/gis")

gdf = gpd.GeoDataFrame(edges, geometry="linestring", crs=4326)
gdf.to_postgis(name="edges", con=engine, if_exists="replace")